/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Local_Admin
 */
public class BuscarTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form BuscarTrabajador
     */
    private VentanaPrincipal principal;
    private ArrayList<Trabajador> listaTrabajador;
    private DefaultTableModel modeloTablaBusquedas;
    private ArrayList<Integer> posTrabajador;

    public BuscarTrabajador() {
        initComponents();
    }

    public BuscarTrabajador(ArrayList<Trabajador> listaTrabajador) {
        initComponents();
        this.listaTrabajador = listaTrabajador;
    }

    public BuscarTrabajador(VentanaPrincipal principal, ArrayList<Trabajador> listaTrabajador) {
        initComponents();
        this.principal = principal;
        this.listaTrabajador = listaTrabajador;
        setVisible(true);
        principal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBuscarPor = new javax.swing.JComboBox<>();
        inputBuscar = new javax.swing.JTextField();
        labelTextoBuscarPor = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();
        buttonSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        comboBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Apellidos", "DNI" }));
        comboBuscarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarPorActionPerformed(evt);
            }
        });

        labelTextoBuscarPor.setText("Buscar por ");

        buttonBuscar.setText("BUSCAR");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        tablaBusqueda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaBusqueda.setToolTipText("");
        tablaBusqueda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaBusqueda);

        buttonSeleccionar.setText("SELECCIONAR");
        buttonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(labelTextoBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputBuscar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBuscarPor)
                            .addComponent(labelTextoBuscarPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBuscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuscarPorActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // TODO add your handling code here:
        ArrayList<Trabajador> listaBuscar = new ArrayList<>();
        String datoIntroducido = null;

        modeloTablaBusquedas = (DefaultTableModel) tablaBusqueda.getModel();
        modeloTablaBusquedas.setRowCount(0);
        if (!inputBuscar.getText().equals("")) {

            switch (comboBuscarPor.getSelectedIndex()) {
                case 0:
                    listaBuscar = Trabajador.buscarListaNombre(listaTrabajador, inputBuscar.getText(), this);
                    break;
                case 1:
                    listaBuscar = Trabajador.buscarListaApellido(listaTrabajador, inputBuscar.getText(), this);
                    break;
                case 2:
                    listaBuscar = Trabajador.buscarListaDni(listaTrabajador, inputBuscar.getText(), this);
                    break;
            };

            if (listaBuscar.size() != 0) {
                for (Trabajador t : listaBuscar) {
                    modeloTablaBusquedas.addRow(new Object[]{t.getDni(), t.getNombre(), t.getApellidos()});
                }
                tablaBusqueda.setModel(modeloTablaBusquedas);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna coincidencia", "No hay coincidencia", JOptionPane.DEFAULT_OPTION);
            }
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void buttonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaBusqueda.getSelectedRow();
        if (filaSeleccionada != -1) {

            principal.setPos(posTrabajador.get(tablaBusqueda.getSelectedRow()));
            principal.visListaTrabajador();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione la fila deseada de los datos del trabajador!", "Seleccionar trabajador", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_buttonSeleccionarActionPerformed

    public void setPosTrabajador(ArrayList posTrabajador) {
        this.posTrabajador = posTrabajador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonSeleccionar;
    private javax.swing.JComboBox<String> comboBuscarPor;
    private javax.swing.JTextField inputBuscar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTextoBuscarPor;
    private javax.swing.JTable tablaBusqueda;
    // End of variables declaration//GEN-END:variables
}
