/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Local_Admin
 */
public class NuevoTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form nuevoTrabajador
     */
    private ArrayList<Trabajador> listaTrabajador = new ArrayList<>();
    private VentanaPrincipal principal;
    private Trabajador trabajadorModifica;

    public NuevoTrabajador() {
        initComponents();
    }

    public NuevoTrabajador(ArrayList<Trabajador> lista, VentanaPrincipal principal) {
        initComponents();
        setVisible(true);
        listaTrabajador = lista;
        this.principal = principal;
        principal.setVisible(false);
    }

    public NuevoTrabajador(ArrayList<Trabajador> lista, VentanaPrincipal principal, int pos) {
        initComponents();
        setVisible(true);
        listaTrabajador = lista;
        this.principal = principal;
        trabajadorModifica = (Trabajador) listaTrabajador.get(pos);
        visDatosTrabajador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTextoNombre = new javax.swing.JLabel();
        labelTextoApellidos = new javax.swing.JLabel();
        labelNuevaContrasena = new javax.swing.JLabel();
        labelComfirmarContrasena = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        inputApellidos = new javax.swing.JTextField();
        buttonRegistrar = new javax.swing.JButton();
        labelTextoDni = new javax.swing.JLabel();
        inputDni = new javax.swing.JTextField();
        inputNuevaContrasena = new javax.swing.JPasswordField();
        inputConfirmarContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelTextoNombre.setText("NOMBRE :");

        labelTextoApellidos.setText("APELLIDOS :");

        labelNuevaContrasena.setText("NUEVA CONTRASEÑA :");

        labelComfirmarContrasena.setText("COMFIRMAR CONTRASEÑA :");

        buttonRegistrar.setText("REGISTRAR");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });

        labelTextoDni.setText("DNI :");

        inputNuevaContrasena.setText("999999");
        inputNuevaContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNuevaContrasenaFocusGained(evt);
            }
        });
        inputNuevaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNuevaContrasenaActionPerformed(evt);
            }
        });

        inputConfirmarContrasena.setText("999999");
        inputConfirmarContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputConfirmarContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputConfirmarContrasenaFocusLost(evt);
            }
        });
        inputConfirmarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputConfirmarContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(buttonRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelComfirmarContrasena)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelNuevaContrasena)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelTextoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTextoDni))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputNombre)
                            .addComponent(inputApellidos)
                            .addComponent(inputDni, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(inputNuevaContrasena)
                            .addComponent(inputConfirmarContrasena))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTextoDni)
                    .addComponent(inputDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTextoNombre)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTextoApellidos)
                    .addComponent(inputApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNuevaContrasena)
                    .addComponent(inputNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComfirmarContrasena)
                    .addComponent(inputConfirmarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(buttonRegistrar)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputConfirmarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputConfirmarContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConfirmarContrasenaActionPerformed

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:
        if (esCompletado()) {
            if (!esContrasenaIgual()) {
                JOptionPane.showMessageDialog(this, "Debe coincidir la misma contraseña las dos veces!", "Error contraseña!", JOptionPane.WARNING_MESSAGE);
            } else {
                if (trabajadorModifica == null) {
                    if (JOptionPane.showConfirmDialog(this, "¿Seguro que desea guardar el trabajador?", "Registrar trabajador nuevo", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                        listaTrabajador.add(new Trabajador(inputNombre.getText(), inputApellidos.getText(), inputNuevaContrasena.getPassword(), inputDni.getText()));

                        Collections.sort(listaTrabajador);
                        principal.visListaTrabajador();

                        JOptionPane.showMessageDialog(this, "Trabajador guardado correctamente!", "Nuevo trabajador", JOptionPane.DEFAULT_OPTION);
                    }
                } else {
                    if (JOptionPane.showConfirmDialog(this, "¿Seguro que desea modificar el trabajador?", "Modificar trabajador", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                        trabajadorModifica.setNombre(inputNombre.getText());
                        trabajadorModifica.setApellidos(inputApellidos.getText());
                        trabajadorModifica.setClave(inputNuevaContrasena.getPassword());
                        trabajadorModifica.setDni(inputDni.getText());

                        Collections.sort(listaTrabajador);
                        principal.visListaTrabajador();

                        JOptionPane.showMessageDialog(this, "Trabajador modificado correctamente!", "Modificación trabajador", JOptionPane.DEFAULT_OPTION);
                    }
                }
                principal.setVisible(true);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error, debe completar todos los campos!", "Campos vacíos!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    private boolean esCompletado() {
        return Utilidades.esNoVacio(inputDni) && Utilidades.esNoVacio(inputApellidos) && Utilidades.esNoVacio(inputConfirmarContrasena)
                && Utilidades.esNoVacio(inputNombre) && Utilidades.esNoVacio(inputNuevaContrasena);
    }

    private boolean esContrasenaIgual() {
        return Arrays.equals(inputNuevaContrasena.getPassword(), inputConfirmarContrasena.getPassword());
    }

    public void visDatosTrabajador() {
        inputApellidos.setText(trabajadorModifica.getApellidos());
        inputNombre.setText(trabajadorModifica.getNombre());
        inputDni.setText(trabajadorModifica.getDni());
    }

    private void inputNuevaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNuevaContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNuevaContrasenaActionPerformed

    private void inputNuevaContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNuevaContrasenaFocusGained
        // TODO add your handling code here:

        if (Arrays.equals(inputNuevaContrasena.getPassword(), new char[]{'9', '9', '9', '9', '9', '9'})) {
            inputNuevaContrasena.setText("");
        }
    }//GEN-LAST:event_inputNuevaContrasenaFocusGained

    private void inputConfirmarContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfirmarContrasenaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inputConfirmarContrasenaFocusLost

    private void inputConfirmarContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfirmarContrasenaFocusGained
        // TODO add your handling code here:
        if (Arrays.equals(inputConfirmarContrasena.getPassword(), new char[]{'9', '9', '9', '9', '9', '9'})) {
            inputConfirmarContrasena.setText("");
        }
    }//GEN-LAST:event_inputConfirmarContrasenaFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        principal.setVisible(true);
        
        //dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JPasswordField inputConfirmarContrasena;
    private javax.swing.JTextField inputDni;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JPasswordField inputNuevaContrasena;
    private javax.swing.JLabel labelComfirmarContrasena;
    private javax.swing.JLabel labelNuevaContrasena;
    private javax.swing.JLabel labelTextoApellidos;
    private javax.swing.JLabel labelTextoDni;
    private javax.swing.JLabel labelTextoNombre;
    // End of variables declaration//GEN-END:variables
}
